import React, { useState, useEffect, useRef } from 'react';
import { getSupabaseConfig, saveSupabaseConfig, getSupabaseClient } from '../services/supabaseClient';
import { authService, DEFAULT_PERMISSIONS } from '../services/authService';
import { dataService } from '../services/dataService';
import { User, Store, UserPermissions, RoleLevel } from '../types';
import { Icons } from '../components/Icons';
import { UsernameBadge } from '../components/UsernameBadge';
import { SVIPBadge } from '../components/SVIPBadge';
import { useUserPermissions, usePermissionContext } from '../contexts/PermissionContext';

export const Settings: React.FC<{ subPage?: string; onThemeChange?: (theme: string) => void }> = ({ subPage = 'config', onThemeChange }) => {
    const [configUrl, setConfigUrl] = useState('');
    const [configKey, setConfigKey] = useState('');
    const [saved, setSaved] = useState(false);
    const [currentTheme, setCurrentTheme] = useState(localStorage.getItem('sw_theme') || 'light');

    useEffect(() => {
        const config = getSupabaseConfig();
        setConfigUrl(config.url);
        setConfigKey(config.key);
    }, [subPage]);

    const handleSaveConfig = () => {
        saveSupabaseConfig(configUrl.trim(), configKey.trim());
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
        window.location.reload(); 
    };

    const handleThemeClick = (theme: string) => {
        setCurrentTheme(theme);
        if (onThemeChange) onThemeChange(theme);
    };
    
    // FULL DATABASE INITIALIZATION SCRIPT (V3.3.0)
    const sqlScript = `
-- STOCKWISE V3.3.0 FULL SCHEMA INITIALIZATION
-- 包含: 多门店(Stores), 拆零商品(Products), 批次效期(Batches), 事务(Transactions), 用户权限(Users)
-- 请在 Supabase SQL Editor 中运行此脚本

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. STORES (门店表)
CREATE TABLE IF NOT EXISTS stores (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    location TEXT,
    is_archived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCTS (商品表 - 支持拆零)
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    sku TEXT,
    category TEXT,
    unit_name TEXT DEFAULT '件',        -- 大单位 (如: 箱)
    split_unit_name TEXT DEFAULT '个',  -- 小单位 (如: 瓶)
    split_ratio INTEGER DEFAULT 1,      -- 换算率 (1箱=多少瓶)
    min_stock_level INTEGER DEFAULT 10,
    image_url TEXT,
    pinyin TEXT,
    bound_store_id TEXT, -- 严格绑定门店 (可选)
    is_archived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BATCHES (批次表 - 核心库存)
CREATE TABLE IF NOT EXISTS batches (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    product_id TEXT REFERENCES products(id),
    store_id TEXT REFERENCES stores(id),
    batch_number TEXT,
    quantity INTEGER DEFAULT 0,  -- 总是以最小单位存储
    expiry_date TIMESTAMPTZ,
    is_archived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TRANSACTIONS (事务日志)
CREATE TABLE IF NOT EXISTS transactions (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    type TEXT NOT NULL, -- IN, OUT, ADJUST, IMPORT, DELETE, RESTORE
    product_id TEXT, -- 弱关联，防止删除商品后日志丢失
    store_id TEXT,
    batch_id TEXT,
    quantity INTEGER NOT NULL,
    balance_after INTEGER,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    note TEXT,
    operator TEXT,
    snapshot_data JSONB, -- 存储操作时的快照
    is_undone BOOLEAN DEFAULT FALSE
);

-- 6. USERS (用户与权限)
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    username TEXT UNIQUE NOT NULL,
    password TEXT,
    role_level INTEGER DEFAULT 9,
    
    -- 扁平化权限字段
    logs_level TEXT DEFAULT 'D',
    announcement_rule TEXT DEFAULT 'VIEW',
    store_scope TEXT DEFAULT 'LIMITED',
    allowed_store_ids TEXT[] DEFAULT '{}',
    show_excel BOOLEAN DEFAULT FALSE,
    view_peers BOOLEAN DEFAULT FALSE,
    view_self_in_list BOOLEAN DEFAULT TRUE,
    hide_perm_page BOOLEAN DEFAULT TRUE,
    hide_audit_hall BOOLEAN DEFAULT TRUE,
    hide_store_management BOOLEAN DEFAULT TRUE,
    only_view_config BOOLEAN DEFAULT FALSE,
    
    is_archived BOOLEAN DEFAULT FALSE,
    face_descriptor TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ANNOUNCEMENTS (公告)
CREATE TABLE IF NOT EXISTS announcements (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    title TEXT NOT NULL,
    content TEXT,
    creator TEXT,
    target_users TEXT[],
    valid_until TIMESTAMPTZ,
    popup_config JSONB,
    is_force_deleted BOOLEAN DEFAULT FALSE,
    read_by TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. SYSTEM AUDIT LOGS (审计日志)
CREATE TABLE IF NOT EXISTS system_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT,
    record_id TEXT,
    operation TEXT,
    old_data JSONB,
    new_data JSONB,
    operator TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 9. RPC: 原子化库存操作 (Transaction + Batch Update)
CREATE OR REPLACE FUNCTION operate_stock(
    p_batch_id TEXT,
    p_qty_change INTEGER,
    p_type TEXT,
    p_note TEXT,
    p_operator TEXT,
    p_snapshot JSONB
) RETURNS VOID AS $$
DECLARE
    v_product_id TEXT;
    v_store_id TEXT;
    v_current_qty INTEGER;
    v_new_qty INTEGER;
BEGIN
    -- 锁定批次行
    SELECT product_id, store_id, quantity INTO v_product_id, v_store_id, v_current_qty 
    FROM batches WHERE id = p_batch_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Batch not found';
    END IF;

    v_new_qty := v_current_qty + p_qty_change;
    
    IF v_new_qty < 0 AND p_type = 'OUT' THEN
         RAISE EXCEPTION 'Stock insufficient';
    END IF;

    -- 更新批次
    UPDATE batches SET quantity = v_new_qty WHERE id = p_batch_id;

    -- 插入事务日志
    INSERT INTO transactions (
        type, product_id, store_id, batch_id, quantity, balance_after, note, operator, snapshot_data
    ) VALUES (
        p_type, v_product_id, v_store_id, p_batch_id, ABS(p_qty_change), v_new_qty, p_note, p_operator, p_snapshot
    );
END;
$$ LANGUAGE plpgsql;

-- 10. Enable Realtime for Users (For Permission Sync)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'users') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE users;
  END IF;
END $$;
`;

    if (subPage === 'config') {
        return (
            <div className="p-4 md:p-8 max-w-4xl mx-auto dark:text-gray-100 flex flex-col gap-6">
                <h1 className="text-2xl font-bold mb-2">连接配置</h1>
                <div className="bg-white dark:bg-gray-900 p-4 md:p-8 rounded-xl shadow-sm border dark:border-gray-700 flex flex-col gap-4 max-w-[100vw] overflow-hidden">
                    <div className="flex flex-col gap-4 w-full">
                        <div className="w-full">
                            <label className="block text-sm font-medium mb-2">Supabase Project URL</label>
                            <input value={configUrl} onChange={(e) => setConfigUrl(e.target.value)} className="w-full rounded-lg border dark:border-gray-600 dark:bg-gray-800 p-3 outline-none dark:text-white break-all" />
                        </div>
                        <div className="w-full">
                            <label className="block text-sm font-medium mb-2">Supabase Anon Key</label>
                            <input 
                                type="password" 
                                value={configKey} 
                                onChange={(e) => setConfigKey(e.target.value)} 
                                onCopy={(e) => e.preventDefault()} 
                                className="w-full rounded-lg border dark:border-gray-600 dark:bg-gray-800 p-3 outline-none dark:text-white break-all select-none" 
                            />
                        </div>
                        
                        <div className="w-full">
                             <div className="flex justify-between items-center mb-2">
                                 <h3 className="font-bold text-sm">数据库初始化 SQL (V3.3.0)</h3>
                                 <button onClick={() => navigator.clipboard.writeText(sqlScript)} className="bg-blue-100 text-blue-700 px-2 py-1 text-xs rounded">复制 SQL</button>
                             </div>
                             <pre className="bg-black text-green-400 p-4 rounded h-40 overflow-auto text-xs font-mono w-full whitespace-pre-wrap break-all">{sqlScript}</pre>
                             <p className="text-xs text-gray-500 mt-1">包含：Stores, Products(Split Unit), Batches(Expiry), Transactions, Users, RPC(operate_stock)</p>
                        </div>

                        <button onClick={handleSaveConfig} className="w-full bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 font-bold mt-2">保存配置</button>
                    </div>
                    {saved && <span className="text-green-600 font-bold text-center">已保存</span>}
                </div>
            </div>
        );
    }

    if (subPage === 'theme') {
        return (
            <div className="p-8 max-w-4xl mx-auto">
                 <h1 className="text-2xl font-bold mb-6 dark:text-white">应用主题</h1>
                 <div className="bg-white dark:bg-gray-900 p-8 rounded-xl shadow-sm border dark:border-gray-700 flex flex-col md:flex-row gap-4">
                     <button onClick={() => handleThemeClick('light')} className={`px-6 py-3 rounded-lg border font-bold ${currentTheme==='light' ? 'bg-blue-50 border-blue-500 text-blue-700' : 'dark:text-white dark:border-gray-600'}`}>浅色 (Light)</button>
                     <button onClick={() => handleThemeClick('dark')} className={`px-6 py-3 rounded-lg border font-bold ${currentTheme==='dark' ? 'bg-gray-700 border-gray-500 text-white' : 'dark:text-white dark:border-gray-600'}`}>深色 (Dark)</button>
                 </div>
            </div>
        );
    }

    if (subPage === 'account') return <AccountSettings />;
    if (subPage === 'perms') return <PermissionsSettings />;
    
    return null;
};

// ... (Rest of the components: PermissionMatrix, PermissionsSettings, AccountSettings, etc. remain unchanged)
// To keep the response concise, I'm omitting the unchanged sub-components, 
// but in a real file update, they would be preserved. 
// Assuming the user copy-pastes this file, I need to include them or instructed to keep them.
// Given the prompt rules "ONLY return the xml... Assume that if you do not provide a file it will not be changed",
// BUT here I am updating a file partially? No, the rule says "Full content of file_1".
// So I must include the FULL content of Settings.tsx.

// ... (Since the previous Settings.tsx content was provided in the prompt, I will reconstruct the full file below)

// ISOLATED PERMISSION MATRIX COMPONENT
interface PermissionMatrixProps {
    userId?: string;
    initialUser: Partial<User>;
    stores: Store[];
    onLocalChange?: (field: string, val: any) => void;
}

const PermissionMatrix: React.FC<PermissionMatrixProps> = ({ userId, initialUser, stores, onLocalChange }) => {
    const [localPerms, setLocalPerms] = useState<Partial<User>>(userId ? {} : initialUser);
    const [loading, setLoading] = useState(!!userId);

    useEffect(() => {
        let active = true;
        if (userId) {
            setLoading(true);
            dataService.getUser(userId).then(freshUser => {
                if (active) {
                    if (freshUser) {
                        setLocalPerms(freshUser);
                    }
                    setLoading(false);
                }
            }).catch(err => {
                console.error("Fetch Perms Error", err);
                if (active) setLoading(false);
            });
        } else {
             setLocalPerms(initialUser);
             setLoading(false);
        }
        return () => { active = false; };
    }, [userId]); 

    const handleUpdate = async (field: keyof User, value: any) => {
        const newState = { ...localPerms, [field]: value };
        setLocalPerms(newState);

        if (userId) {
            try {
                await dataService.updateUser(userId, { [field]: value });
                console.log(`[PermissionMatrix] Synced ${field} for user ${userId}`);
            } catch (error: any) {
                console.error("DB Update Failed:", error);
                alert(`权限保存失败，请重试: ${error.message}`);
                setLocalPerms(prev => ({ ...prev, [field]: localPerms[field] }));
            }
        } else {
            if (onLocalChange) onLocalChange(field as string, value);
        }
    };

    if (loading) {
        return (
            <div className="p-12 flex flex-col items-center justify-center space-y-4 text-gray-500 bg-gray-50 dark:bg-gray-800/50 rounded-lg border-2 border-dashed border-gray-200 dark:border-gray-700">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                <div className="text-sm font-medium">正在同步最新权限配置...</div>
            </div>
        );
    }

    return (
        <div className="space-y-4 animate-fade-in">
            <h3 className="font-bold text-lg dark:text-white border-b pb-2 dark:border-gray-700 flex justify-between items-center">
                <span>权限矩阵配置</span>
                <span className="text-xs font-normal text-green-600 bg-green-50 dark:bg-green-900/30 px-2 py-1 rounded">
                    {userId ? '● 实时独立保存' : '● 保存需点击底部按钮'}
                </span>
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg border dark:border-gray-700 shadow-sm">
                    <h3 className="font-bold dark:text-white mb-3 flex items-center gap-2"><Icons.Sparkles size={16}/> 日志权限 (Log Level)</h3>
                    <div className="flex md:flex-col gap-3 overflow-x-auto pb-2 md:pb-0 snap-x hide-scrollbar md:overflow-visible">
                        {[
                            { val: 'A', label: 'A级: 查看所有 + 任意撤销 (最高)' },
                            { val: 'B', label: 'B级: 查看所有 + 仅撤销低等级' },
                            { val: 'C', label: 'C级: 查看所有 + 仅撤销自己' },
                            { val: 'D', label: 'D级: 仅查看自己 + 仅撤销自己' },
                        ].map(opt => (
                            <label key={opt.val} className={`min-w-[85%] md:min-w-0 snap-center flex items-center gap-2 cursor-pointer p-2 rounded transition-all duration-200 shrink-0 border md:border-transparent ${localPerms.logs_level === opt.val ? 'bg-blue-100 dark:bg-blue-900/30 border-blue-200 dark:border-blue-800 shadow-sm transform scale-[1.02]' : 'bg-white md:bg-transparent dark:bg-gray-700/50 md:dark:bg-transparent border-gray-100 dark:border-gray-700 hover:bg-gray-200 dark:hover:bg-gray-700'}`}>
                                <input 
                                   type="radio" 
                                   name="logs_level" 
                                   checked={localPerms.logs_level === opt.val} 
                                   onChange={() => handleUpdate('logs_level', opt.val)}
                                   className="accent-blue-500 w-4 h-4 ml-2 md:ml-0"
                                />
                                <span className={`text-sm ${localPerms.logs_level === opt.val ? 'text-blue-700 dark:text-blue-300 font-bold' : 'text-gray-600 dark:text-gray-400'}`}>{opt.label}</span>
                            </label>
                        ))}
                    </div>
                </div>

                <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg border dark:border-gray-700 shadow-sm space-y-6">
                    <div>
                        <h3 className="font-bold dark:text-white mb-3">公告权限</h3>
                        <div className="flex gap-4 overflow-x-auto pb-2 md:pb-0">
                            <label className="flex items-center gap-2 cursor-pointer group shrink-0">
                                <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${localPerms.announcement_rule === 'PUBLISH' ? 'border-blue-500 bg-blue-500' : 'border-gray-400'}`}>
                                    {localPerms.announcement_rule === 'PUBLISH' && <div className="w-2 h-2 bg-white rounded-full"></div>}
                                </div>
                                <input type="radio" className="hidden" checked={localPerms.announcement_rule === 'PUBLISH'} onChange={() => handleUpdate('announcement_rule', 'PUBLISH')} />
                                <span className={`text-sm ${localPerms.announcement_rule === 'PUBLISH' ? 'font-bold text-blue-600 dark:text-blue-400' : 'dark:text-gray-300'}`}>发布 & 接收</span>
                            </label>
                            <label className="flex items-center gap-2 cursor-pointer group shrink-0">
                                <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${localPerms.announcement_rule === 'VIEW' ? 'border-blue-500 bg-blue-500' : 'border-gray-400'}`}>
                                    {localPerms.announcement_rule === 'VIEW' && <div className="w-2 h-2 bg-white rounded-full"></div>}
                                </div>
                                <input type="radio" className="hidden" checked={localPerms.announcement_rule === 'VIEW'} onChange={() => handleUpdate('announcement_rule', 'VIEW')} />
                                <span className={`text-sm ${localPerms.announcement_rule === 'VIEW' ? 'font-bold text-blue-600 dark:text-blue-400' : 'dark:text-gray-300'}`}>仅接收</span>
                            </label>
                        </div>
                    </div>
                    <div>
                        <h3 className="font-bold dark:text-white mb-3">门店范围策略</h3>
                        <div className="flex gap-4 mb-2 items-center overflow-x-auto pb-2 md:pb-0">
                            <label className="flex items-center gap-2 cursor-pointer shrink-0">
                                <input type="radio" checked={localPerms.store_scope === 'GLOBAL'} onChange={() => handleUpdate('store_scope', 'GLOBAL')} className="accent-blue-500"/>
                                <span className="text-sm dark:text-gray-300">全局 (Global)</span>
                            </label>
                            <label className="flex items-center gap-2 cursor-pointer shrink-0">
                                <input type="radio" checked={localPerms.store_scope === 'LIMITED'} onChange={() => handleUpdate('store_scope', 'LIMITED')} className="accent-blue-500"/>
                                <span className="text-sm dark:text-gray-300">受限</span>
                            </label>
                        </div>
                        {localPerms.store_scope === 'LIMITED' && (
                            <div className="border rounded dark:border-gray-600 p-3 bg-white dark:bg-gray-700 animate-fade-in mt-2 relative">
                                <div className="absolute -top-2 left-20 w-3 h-3 bg-white dark:bg-gray-700 border-t border-l dark:border-gray-600 transform rotate-45"></div>
                                <h3 className="font-bold text-xs mb-2 dark:text-gray-300 text-blue-600">选择可见门店 (多选)</h3>
                                <div className="grid grid-cols-1 gap-2 max-h-40 overflow-y-auto custom-scrollbar">
                                    {stores.map(s => (
                                        <label key={s.id} className="flex items-center gap-2 text-xs dark:text-gray-300 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-600 p-1 rounded">
                                            <input 
                                               type="checkbox" 
                                               checked={localPerms.allowed_store_ids?.includes(s.id)}
                                               onChange={e => {
                                                   const set = new Set<string>(localPerms.allowed_store_ids || []);
                                                   if(e.target.checked) set.add(s.id); else set.delete(s.id);
                                                   handleUpdate('allowed_store_ids', Array.from(set));
                                               }}
                                               className="accent-blue-500 rounded"
                                            />
                                            {s.name}
                                        </label>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg border dark:border-gray-700 shadow-sm">
                    <h3 className="font-bold dark:text-white mb-3">功能开关</h3>
                    <div className="grid grid-cols-1 gap-3">
                        <ToggleRow label="显示 Excel 导出" checked={!!localPerms.show_excel} onChange={(v) => handleUpdate('show_excel', v)} />
                        <ToggleRow label="列表显示自己 (Show Self)" checked={!!localPerms.view_self_in_list} onChange={(v) => handleUpdate('view_self_in_list', v)} />
                        <ToggleRow label="可见同级 (Visible Peers)" checked={!!localPerms.view_peers} onChange={(v) => handleUpdate('view_peers', v)} />
                        
                        <div className="h-px bg-gray-200 dark:bg-gray-700 my-1"></div>
                        
                        <ToggleRow label="隐藏权限页 (Safety)" checked={!!localPerms.hide_perm_page} onChange={(v) => handleUpdate('hide_perm_page', v)} danger />
                        <ToggleRow label="隐藏审计大厅 (Safety)" checked={!!localPerms.hide_audit_hall} onChange={(v) => handleUpdate('hide_audit_hall', v)} danger />
                        <ToggleRow label="隐藏门店管理 (增删改)" checked={!!localPerms.hide_store_management} onChange={(v) => handleUpdate('hide_store_management', v)} danger />
                        <ToggleRow label="仅显示配置页 (锁定)" checked={!!localPerms.only_view_config} onChange={(v) => handleUpdate('only_view_config', v)} danger />
                    </div>
                </div>
            </div>
        </div>
    );
};

const ToggleRow = ({ label, checked, onChange, danger }: any) => (
    <div 
        onClick={() => onChange(!checked)}
        className={`flex items-center justify-between p-2 rounded cursor-pointer transition-colors ${checked ? (danger ? 'bg-red-50 dark:bg-red-900/20' : 'bg-blue-50 dark:bg-blue-900/20') : 'hover:bg-gray-200 dark:hover:bg-gray-700'}`}
    >
        <span className={`text-sm ${danger ? (checked ? 'text-red-600 font-bold' : 'text-gray-600 dark:text-gray-400') : (checked ? 'text-blue-700 dark:text-blue-300 font-bold' : 'text-gray-600 dark:text-gray-400')}`}>{label}</span>
        <div className={`w-10 h-5 rounded-full relative transition-colors ${checked ? (danger ? 'bg-red-500' : 'bg-blue-500') : 'bg-gray-300 dark:bg-gray-600'}`}>
            <div className={`absolute top-0.5 w-4 h-4 bg-white rounded-full shadow-sm transition-transform duration-200 ${checked ? 'left-5.5' : 'left-0.5'}`}></div>
        </div>
    </div>
);

const PermissionsSettings = () => {
    const currentUser = authService.getCurrentUser();
    const { currentUserPermissions } = usePermissionContext(); 
    const client = getSupabaseClient();

    const [subordinates, setSubordinates] = useState<User[]>([]);
    const [stores, setStores] = useState<Store[]>([]);
    const [isUserModalOpen, setIsUserModalOpen] = useState(false);
    const [editingUser, setEditingUser] = useState<User | null>(null);
    const [userFormData, setUserFormData] = useState<Partial<User>>({});
    
    useEffect(() => {
        loadUsers();
    }, []);

    const loadUsers = async () => {
        if (!currentUser) return;
        const [users, allStores] = await Promise.all([dataService.getUsers(), dataService.getStores()]);
        
        const myPerms = currentUserPermissions;
        let subs: User[] = [];
        
        if (myPerms.view_peers) {
             subs = users.filter(u => u.role_level >= currentUser.role_level);
        } else {
             subs = users.filter(u => u.role_level > currentUser.role_level);
        }
        
        if (!myPerms.view_self_in_list) {
            subs = subs.filter(u => u.id !== currentUser.id);
        } else {
            if (!subs.find(u => u.id === currentUser.id)) {
                const me = users.find(u => u.id === currentUser.id);
                if (me) subs.unshift(me);
            }
        }
        setSubordinates(subs);
        setStores(allStores);
    };

    const handleEditUser = (user: User | null) => {
        if (user) {
            if (currentUser && user.role_level === currentUser.role_level && user.id !== currentUser.id) {
                if (currentUser.role_level !== 0) {
                    alert("无权修改同级用户 (仅可查看/删除/新建)");
                    return;
                }
            }
            if (currentUser && user.role_level < currentUser.role_level) {
                 alert("无权修改上级用户");
                 return;
            }
            setEditingUser(user);
            setUserFormData({
                ...user,
                logs_level: user.logs_level || 'D',
                announcement_rule: user.announcement_rule || 'VIEW',
                store_scope: user.store_scope || 'LIMITED',
                show_excel: user.show_excel ?? false,
                view_peers: user.view_peers ?? false,
                view_self_in_list: user.view_self_in_list ?? true,
                hide_perm_page: user.hide_perm_page ?? true,
                hide_audit_hall: user.hide_audit_hall ?? true,
                hide_store_management: user.hide_store_management ?? true,
                only_view_config: user.only_view_config ?? false
            });
        } else {
            setEditingUser(null);
            setUserFormData({
                username: '', password: '123', 
                role_level: (currentUserPermissions.view_peers ? currentUser?.role_level : (currentUser?.role_level || 0) + 1) as RoleLevel,
                allowed_store_ids: [],
                logs_level: 'D',
                announcement_rule: 'VIEW',
                store_scope: 'LIMITED',
                show_excel: false,
                view_peers: false,
                view_self_in_list: true,
                hide_perm_page: true,
                hide_audit_hall: true,
                hide_store_management: true,
                only_view_config: false
            });
        }
        setIsUserModalOpen(true);
    };

    const handleSaveUser = async () => {
        if (!userFormData.username) return alert("用户名必填");
        
        const inputLevel = Number(userFormData.role_level);
        const myLevel = currentUser?.role_level || 0;
        
        if (inputLevel < myLevel) return alert("不能将用户等级设置高于您自己的等级");

        if (editingUser) {
             if (inputLevel < editingUser.role_level) return alert("权限等级只能往低修改 (数字变大，不可往高修改！");
             
             const basicUpdates: Partial<User> = {
                 username: userFormData.username,
                 password: userFormData.password,
                 role_level: userFormData.role_level
             };
             await dataService.updateUser(editingUser.id, basicUpdates);
        } else {
             await dataService.createUser(userFormData as any);
        }

        setIsUserModalOpen(false);
        loadUsers();
    };

    const handleDeleteUser = async (u: User) => {
        if (currentUser && u.role_level < currentUser.role_level) return alert("无法删除上级用户");
        if(confirm("确定删除该用户？(软删除)")) { await dataService.deleteUser(u.id); loadUsers(); }
    };

    const updateForm = (updates: Partial<User>) => {
        setUserFormData(prev => ({ ...prev, ...updates }));
    };

    const handleNewUserPermissionChange = (field: string, val: any) => {
        setUserFormData(prev => ({ ...prev, [field]: val }));
    };

    return (
        <div className="p-4 md:p-8 max-w-7xl mx-auto dark:text-gray-100 flex flex-col gap-8">
             
             <div className="bg-white dark:bg-gray-800 rounded-xl border dark:border-gray-700 p-6 shadow-sm">
                 <div className="flex justify-between items-center mb-6">
                     <h2 className="text-xl font-bold dark:text-white">用户管理</h2>
                     <button onClick={() => handleEditUser(null)} className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2">
                         <Icons.Plus size={20}/> 新增用户
                     </button>
                 </div>

                 <div className="overflow-x-auto">
                     <table className="w-full text-left min-w-[600px]">
                         <thead className="bg-gray-50 dark:bg-gray-900 border-b dark:border-gray-700">
                             <tr>
                                 <th className="p-4">用户</th>
                                 <th className="p-4">等级</th>
                                 <th className="p-4">日志权限</th>
                                 <th className="p-4">门店范围</th>
                                 <th className="p-4 text-right">操作</th>
                             </tr>
                         </thead>
                         <tbody className="divide-y dark:divide-gray-700">
                             {subordinates.map(u => {
                                 const p = u.permissions; 
                                 return (
                                     <tr key={u.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                                         <td className="p-4"><UsernameBadge name={u.username} roleLevel={u.role_level} /></td>
                                         <td className="p-4"><span className="bg-gray-200 dark:bg-gray-700 px-2 py-1 rounded text-xs font-mono">{u.role_level}</span></td>
                                         <td className="p-4"><span className="bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-1 rounded text-xs font-bold">{p.logs_level}级</span></td>
                                         <td className="p-4 text-sm text-gray-500 dark:text-gray-400">{p.store_scope === 'GLOBAL' ? '全局 (Global)' : `受限 (${u.allowed_store_ids.length})`}</td>
                                         <td className="p-4 text-right space-x-2">
                                             <button onClick={() => handleEditUser(u)} className="text-blue-600 font-bold hover:underline">编辑</button>
                                             <button onClick={() => handleDeleteUser(u)} className="text-red-600 font-bold hover:underline">删除</button>
                                         </td>
                                     </tr>
                                 );
                             })}
                         </tbody>
                     </table>
                 </div>
             </div>

             {isUserModalOpen && (
                 <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
                     <div className="bg-white dark:bg-gray-900 rounded-xl w-full max-w-4xl shadow-2xl flex flex-col max-h-[90vh]">
                         <div className="p-6 border-b dark:border-gray-700 flex justify-between items-center shrink-0">
                             <h2 className="text-xl font-bold dark:text-white">{editingUser ? '编辑用户 & 权限配置' : '新增用户 & 权限配置'}</h2>
                             <button onClick={() => setIsUserModalOpen(false)}><Icons.Minus size={24} className="dark:text-white"/></button>
                         </div>
                         
                         <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
                             <div className="space-y-4">
                                 <h3 className="font-bold text-lg dark:text-white border-b pb-2 dark:border-gray-700">基本信息</h3>
                                 <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                     <div>
                                        <label className="block text-sm font-bold mb-1 dark:text-gray-300">用户名</label>
                                        <input value={userFormData.username} onChange={e => updateForm({username: e.target.value})} className="w-full border p-2 rounded dark:bg-gray-800 dark:border-gray-600 dark:text-white"/>
                                     </div>
                                     <div>
                                        <label className="block text-sm font-bold mb-1 dark:text-gray-300">密码</label>
                                        <input value={userFormData.password} onChange={e => updateForm({password: e.target.value})} className="w-full border p-2 rounded dark:bg-gray-800 dark:border-gray-600 dark:text-white"/>
                                     </div>
                                     <div>
                                         <label className="block text-sm font-bold mb-1 dark:text-gray-300">管理等级 (0-9)</label>
                                         <input 
                                             type="number" 
                                             min={currentUser?.role_level} 
                                             max="9" 
                                             value={userFormData.role_level} 
                                             onChange={e => updateForm({role_level: Number(e.target.value) as RoleLevel})} 
                                             className="w-full border p-2 rounded dark:bg-gray-800 dark:border-gray-600 dark:text-white"
                                         />
                                         <p className="text-xs text-red-400 mt-1">
                                             * &gt;= {currentUser?.role_level} (您的等级)<br/>
                                             {editingUser && `* 编辑时只能调低等级 (数字变大，当前: ${editingUser.role_level})`}
                                         </p>
                                     </div>
                                 </div>
                             </div>

                             <PermissionMatrix 
                                 key={editingUser ? editingUser.id : 'new_user'}
                                 userId={editingUser?.id}
                                 initialUser={editingUser ? {} : userFormData} 
                                 stores={stores} 
                                 onLocalChange={handleNewUserPermissionChange} 
                             />
                             
                         </div>
                         <div className="p-4 border-t dark:border-gray-700 bg-gray-50 dark:bg-gray-800 flex justify-end gap-3 rounded-b-xl shrink-0">
                             <button onClick={() => setIsUserModalOpen(false)} className="px-4 py-2 text-gray-500 font-bold">取消</button>
                             <button onClick={handleSaveUser} className="px-6 py-2 bg-blue-600 text-white rounded font-bold hover:bg-blue-700 shadow">
                                 {editingUser ? '保存基本信息' : '创建用户'}
                             </button>
                         </div>
                     </div>
                 </div>
             )}
        </div>
    );
};

const FaceSetup = ({ user, onSuccess, onCancel }: any) => {
    const videoRef = useRef<HTMLVideoElement>(null);
    const [status, setStatus] = useState('初始化相机...');
    useEffect(() => {
        navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' } })
            .then(stream => { if(videoRef.current) videoRef.current.srcObject = stream; setStatus("请将脸部对准摄像头"); })
            .catch(err => setStatus("相机访问失败: " + err.message));
        return () => { if(videoRef.current?.srcObject) (videoRef.current.srcObject as MediaStream).getTracks().forEach(t => t.stop()); };
    }, []);
    const capture = async () => {
        if (!videoRef.current) return;
        const canvas = document.createElement('canvas');
        canvas.width = videoRef.current.videoWidth;
        canvas.height = videoRef.current.videoHeight;
        canvas.getContext('2d')?.drawImage(videoRef.current, 0, 0);
        await dataService.updateUser(user.id, { face_descriptor: canvas.toDataURL('image/jpeg', 0.8) });
        onSuccess();
    };
    return (
        <div className="fixed inset-0 bg-black/80 z-[100] flex items-center justify-center p-4">
            <div className="bg-white dark:bg-gray-900 rounded-xl p-6 w-full max-w-sm flex flex-col items-center gap-4">
                <h3 className="font-bold text-lg dark:text-white">人脸识别设置</h3>
                <div className="w-64 h-64 bg-black rounded-full overflow-hidden border-4 border-blue-500 relative">
                    <video ref={videoRef} autoPlay playsInline muted className="w-full h-full object-cover"></video>
                </div>
                <p className="text-sm text-gray-500">{status}</p>
                <div className="flex gap-4 w-full"><button onClick={onCancel} className="flex-1 py-2 text-gray-500">取消</button><button onClick={capture} className="flex-1 py-2 bg-blue-600 text-white rounded font-bold">录入</button></div>
            </div>
        </div>
    );
};

const AccountSettings = () => {
    const user = authService.getCurrentUser();
    const [form, setForm] = useState({ username: '', password: '' });
    const [showPass, setShowPass] = useState(false);
    const [lowerUsers, setLowerUsers] = useState<User[]>([]);
    const [showFaceSetup, setShowFaceSetup] = useState(false);
    useEffect(() => {
        if (user) {
            setForm({ username: user.username, password: user.password || '' });
            dataService.getUsers().then(users => { setLowerUsers(users.filter(u => u.role_level > user.role_level)); });
        }
    }, []);
    const handleSave = async () => {
        if (!user) return;
        await dataService.updateUser(user.id, form);
        sessionStorage.setItem('sw_session_user', JSON.stringify({ ...user, ...form }));
        alert("保存成功"); window.location.reload();
    };
    return (
        <div className="p-4 md:p-8 max-w-4xl mx-auto dark:text-gray-100">
            {(user?.role_level === 0 || user?.role_level === 1) && (<div className="mb-6 flex justify-center"><SVIPBadge name={user?.username || ''} roleLevel={user?.role_level} className="w-full max-w-md shadow-2xl scale-110" /></div>)}
            <h1 className="text-2xl font-bold mb-6">账户设置</h1>
            <div className="grid md:grid-cols-2 gap-8">
                <div className="bg-white dark:bg-gray-900 p-6 md:p-8 rounded-xl shadow-sm border dark:border-gray-700 space-y-6 w-full">
                    <h3 className="font-bold border-b pb-2 dark:border-gray-700">基本信息</h3>
                    <div><label className="block text-sm font-bold text-gray-500 uppercase mb-1">ID</label><div className="bg-gray-100 dark:bg-gray-800 p-2 rounded text-xs text-gray-500 font-mono">{user?.id}</div></div>
                    <div><label className="block text-sm font-bold mb-1">用户名</label><input value={form.username} onChange={e => setForm({...form, username: e.target.value})} className="w-full border p-3 rounded dark:bg-gray-800 dark:border-gray-600 dark:text-white"/></div>
                    <div><label className="block text-sm font-bold mb-1">密码</label><div className="relative"><input type={showPass?"text":"password"} value={form.password} onChange={e => setForm({...form, password: e.target.value})} className="w-full border p-3 rounded dark:bg-gray-800 dark:border-gray-600"/><button onClick={()=>setShowPass(!showPass)} className="absolute right-3 top-3 text-gray-400">👁</button></div></div>
                    <button onClick={()=>setShowFaceSetup(true)} className={`w-full py-3 rounded font-bold border ${user?.face_descriptor?'border-green-500 text-green-600 bg-green-50':'border-gray-300 text-gray-600'}`}>{user?.face_descriptor?'重录人脸':'设置人脸'}</button>
                    <button onClick={handleSave} className="w-full py-3 rounded font-bold bg-blue-600 text-white hover:bg-blue-700 shadow-md">保存变更</button>
                    <button onClick={() => {if(confirm("退出?")) authService.logout();}} className="w-full py-3 rounded font-bold border border-red-200 text-red-600 hover:bg-red-50 dark:border-red-900 dark:hover:bg-red-900/20">退出</button>
                </div>
                <div className="bg-white dark:bg-gray-900 p-6 md:p-8 rounded-xl shadow-sm border dark:border-gray-700 h-fit w-full">
                     <h3 className="font-bold border-b pb-2 dark:border-gray-700 mb-4">快速切换</h3>
                     <div className="max-h-60 overflow-y-auto custom-scrollbar border rounded dark:border-gray-700">
                         {lowerUsers.map(u => (<button key={u.id} onClick={() => authService.switchAccount(u)} className="w-full text-left p-3 hover:bg-gray-50 dark:hover:bg-gray-800 border-b dark:border-gray-800 flex justify-between items-center"><UsernameBadge name={u.username} roleLevel={u.role_level} /><span className="text-xs bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">Lv.{u.role_level}</span></button>))}
                     </div>
                </div>
            </div>
            {showFaceSetup && <FaceSetup user={user} onSuccess={()=>{setShowFaceSetup(false); alert("成功"); window.location.reload();}} onCancel={()=>setShowFaceSetup(false)} />}
        </div>
    );
};